# Expression generated by brave-update.sh; do not edit it by hand!
rec {
  pname = "brave-origin-nightly";
  version = "1.94.81";
  channel = "nightly";
  flavor = "origin";

  archives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-cycA7F7YdtWfsjHIe2PFXhcZZuwxdAdF3jco7yjILYk=";
    };
  };
}
