# Expression generated by brave-update.sh; do not edit it by hand!
rec {
  pname = "brave-origin-beta";
  version = "1.98.48";
  channel = "beta";
  flavor = "origin";

  archives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-beta_${version}_amd64.deb";
      hash = "sha256-a55tH6t+sUHhXt89NUn2bQhRXvMuL67Xd3tMtgaB4Fo=";
    };
  };
}
