# Expression generated by update.sh; do not edit it by hand!
rec {
  pname = "brave-origin-nightly";
  version = "1.92.21";
  channel = "nightly";
  flavor = "origin";

  archives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-sKkkuMyDNQzofhdRC1OXCfCtUyawtbpnDalI+caAwew=";
    };
  };
}
